version: '3'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        restart: unless-stopped
        environment:
            ZOOKEEPER_CLIENT_PORT: 32181 
            ZOOKEEPER_TICK_TIME: 2000 
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 32181:32181
  
    kafka:
        image: confluentinc/cp-kafka:latest
        restart: unless-stopped
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://46.101.87.98:29092 
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
    kafkaDashboard:
        image: provectuslabs/kafka-ui:latest
        restart: always
        ports:
            - 5001:8080
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

